### ISSUE TITLE
vs code 添加svn 插件

### ISSUE THREAD

**Issue by huangshuwei** [huangshuwei/blog#37]
### 前言
vs code 中 git 相关插件很丰富，对于 svn 插件却不是那么友好。找了个勉强能用的 svn 插件，特此记录。

### 安装 svn 插件
通过搜索关键字 “svn”，试了几个，最终选择了这个插件（作者为：Chris Johnston）：
![image](https://user-images.githubusercontent.com/6047141/75967686-2649c500-5f07-11ea-95a0-f95ecaf3d52e.png)

### 插件配置

插件配置文件中填入此节点，告知vs code svn 的路径：
```
"svn.path": "C:\\Program Files\\TortoiseSVN\\bin\\svn.exe"
```

> 除此之外 vs code 的侧边栏会出现这个插件的 tab，如果不喜欢禁用即可。我是觉得用处不大
![image](https://user-images.githubusercontent.com/6047141/75968262-0c5cb200-5f08-11ea-99dd-ac431dc71344.png)

### 效果
效果不尽人意，无论选中了文件或者文件夹功能并不丰富。目前有两个功能算是满意，一是可以实时显示当前文件或文件夹的状态（是否被修改），另一个可以还原修改

### 用户体验
用了一段时间，体验非常差，svn 代码修改，但编译器中无法体现变化。不推荐使用，已卸载

--完--

**Comment by bf109f** [comment]
svn怎么设置能像git一样标出变更文件

![Image](https://github.com/user-attachments/assets/705f4024-daa0-4e70-9444-eb8aba1499dc)
目前svn是这样的

![Image](https://github.com/user-attachments/assets/8eecaae2-fdf9-4398-94e2-7bbf6a656d6b)

**Comment by bf109f** [comment]
找到插件了，哦吼吼

![Image](https://github.com/user-attachments/assets/73681033-4b29-447b-a824-5e4626970006)
